### PR TITLE
Update n_to_bits_movemask() to not require BMI2

### PR DESCRIPTION
**Pull request by aqrit**

### CODE REVIEW

**Comment by Daniel-Liu-c0deb0t** [comment]
Hey, thanks for the PR. Do you know how much faster this is compared to the BMI2 version?

**Comment by aqrit** [comment]
This and the BMI2 version are the same speed on my Coffee Lake desktop (~29.5 GiB/s).
`_pdep_u64` on AMD can cost hundreds of cycles, though.

---

Random ideas for `n_to_bits2`:
One could multiply bytes by 5^2, 5^1, or 5^0 using a `_mm256_shuffle_epi8()`.
FastPFor might have a trick for packing 7-bit values together.

**Comment by Daniel-Liu-c0deb0t** [comment]
Thanks! I'm a bit busy right now, so I will have to think about this a little more and merge this later.

**Comment by Daniel-Liu-c0deb0t** [comment]
Hey @aqrit, I've merged the PR. Once again, thanks for your contribution!

**Pull request merged**
